version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      gomod-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "pip"
    directory: "/.devcontainer"
    schedule:
      interval: daily
    groups:
      pip-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "docker"
    directory: "/deployments"
    schedule:
      interval: daily
    groups:
      docker-dependencies:
        update-types:
        - "minor"
        - "patch"
