version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    groups:
      minor_and_patch_group_bump:
        update-types:
        - "minor"
        - "patch"
