name: test1

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - master
  push:
    branches:
      - main

# permissions:
#   contents: write

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
