name: Callee Workflow

on:
  workflow_call:
    inputs:
      something:
        required: true
        type: number

jobs:
  callee-job:
    runs-on: ubuntu-latest
    steps:
      - name: Callee step
        run: |
          echo "HERE!!!: " ${{ inputs.additional_arguments }}
        shell: bash
