name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run script file
        run: |
           pwd
           ls
        shell: bash

      - name: Get Chart Version from helm
        id: chart_version
        uses: mikefarah/yq@master
        with:
          cmd: yq .version charts/ramir-base-chart/Chart.yaml

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0
        with:
          name: ramir-base-chart
          repository: ${{ github.repository }}/charts
          tag: ${{ steps.chart_version.outputs.result  }}
          # path: # Defaults to charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          # update_dependencies: 'true' # Defaults to false
