name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Chart Version and App Version from helm 
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        id: get_chart_yaml_values
        with:
          file: charts/ramir-base-chart/Chart.yaml
          chartversion: version

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ramir-base-chart
          repository: ${{ github.repository }}/charts
          tag: ${{ steps.get_chart_yaml_values.outputs.chartversion  }}
          # path: # Defaults to charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          # update_dependencies: 'true' # Defaults to false
