name: Test Workflow

on:
  workflow_dispatch:
  push:

vars:
  SOMETHING: 1000
jobs:
  test:
    name: call workflow
    uses: ./.github/workflows/callee.yml
    secrets: inherit
    with:
      something: ${{ vars.SOMETHING }}
