name: test1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test1:
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
