name: work2

# concurrency: ${{ github.workflow }}-${{ github.ref }}
concurrency: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
on:
  workflow_dispatch:
  pull_request_target:
  push:
#comment3
jobs:
  sleepjob:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        env:
          TEST_GITHUB_REF: ${{github.ref}}
        run: |
          echo "github.ref: $GITHUB_REF"
          echo "TEST_GITHUB_REF: $TEST_GITHUB_REF"
          echo sleeping...
          sleep 30
