name: work1

on:
  workflow_dispatch:
  push:
#comment2
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: try1

      - name: Head Hash
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd try1
          git ls-remote -q | grep refs/heads/main$ | awk '{print $1}' | xargs git rev-parse --short
          git log --max-count=1
      
      - name: Sleep
        run: |
          echo sleeping...
          sleep 60
      
      - name: Checkout2
        uses: actions/checkout@v3
        with:
          path: try2
  
      - name: Head Hash2
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd try2
          git ls-remote -q | grep refs/heads/main$ | awk '{print $1}' | xargs git rev-parse --short
          git log --max-count=1