name: work1

on:
  workflow_dispatch:
  push:
#comment5
jobs:
  gethash:
    runs-on: ubuntu-latest
    outputs:
      headhash1: ${{ steps.headhash1.outputs.headhash1 }}
      headhash2: ${{ steps.headhash1.outputs.headhash2 }}
    steps:
      - name: Checkout1
        uses: actions/checkout@v3
        with:
          path: try1

      - name: Head Hash1
        id: headhash1
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd try1
          git ls-remote -q | grep refs/heads/main$ | awk '{print $1}' | xargs git rev-parse --short
          git log --max-count=1
          git rev-parse --short HEAD
          sha=$(git rev-parse HEAD)
          echo "headhash1=$sha" >> "$GITHUB_OUTPUT"

      - name: Sleep
        run: |
          echo sleeping...
          sleep 30
      
      - name: Checkout2
        uses: actions/checkout@v3
        with:
          ref: main
          path: try2
  
      - name: Head Hash2
        id: headhash2
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd try2
          git ls-remote -q | grep refs/heads/main$ | awk '{print $1}' | xargs git rev-parse --short
          git log --max-count=1
          git rev-parse --short HEAD
          sha=$(git rev-parse HEAD)
          echo "headhash1=$sha" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: gethash
    steps:
      - env:
          HEADHASH1: ${{needs.gethash.outputs.headhash1}}
          HEADHASH2: ${{needs.gethash.outputs.headhash2}}
        run: echo "$HEADHASH1 $HEADHASH2"